@echo off
REM Windows Setup Script for API-Only Mode
REM This script helps configure the project for API-only mode (no database required)

echo ==========================================
echo Patient Form Monitor - Windows Setup
echo API-Only Mode (No Database Required)
echo ==========================================
echo.

REM Check if Python is installed
python --version >nul 2>&1
if errorlevel 1 (
    echo ERROR: Python is not installed or not in PATH
    echo.
    echo Please install Python from https://www.python.org/downloads/
    echo IMPORTANT: Check "Add Python to PATH" during installation
    echo.
    pause
    exit /b 1
)

echo [1/5] Checking Python installation...
python --version
echo OK
echo.

REM Check if pip is available
python -m pip --version >nul 2>&1
if errorlevel 1 (
    echo ERROR: pip is not available
    echo Installing pip...
    python -m ensurepip --upgrade
)

echo [2/5] Installing Python dependencies...
python -m pip install -r requirements.txt
if errorlevel 1 (
    echo ERROR: Failed to install dependencies
    pause
    exit /b 1
)
echo OK
echo.

echo [3/5] Installing Playwright browsers...
python -m playwright install chromium
if errorlevel 1 (
    echo WARNING: Playwright installation may have failed
    echo You may need to run: python -m playwright install chromium
)
echo OK
echo.

echo [4/5] Setting up environment file...
if exist .env (
    echo .env file already exists
    echo.
    set /p OVERWRITE="Do you want to overwrite it? (y/N): "
    if /i not "%OVERWRITE%"=="y" (
        echo Keeping existing .env file
        goto :config_check
    )
)

echo.
echo ==========================================
echo Environment Configuration
echo ==========================================
echo.

set /p API_URL="Enter your API endpoint URL (e.g., https://app.example.com): "
if "%API_URL%"=="" (
    echo ERROR: API_URL is required
    pause
    exit /b 1
)

set /p QUEUE_URL="Enter Solvhealth queue URL (press Enter for default): "
if "%QUEUE_URL%"=="" set QUEUE_URL=https://manage.solvhealth.com/queue?location_ids=AXjwbE

set /p API_TOKEN="Enter API token (optional, press Enter to skip): "

echo.
echo Creating .env file...
(
    echo # Patient Form Monitor - API-Only Configuration
    echo # Generated by setup-windows-api-only.bat
    echo.
    echo # Required: API Configuration
    echo API_URL=%API_URL%
) > .env

if not "%API_TOKEN%"=="" (
    echo API_TOKEN=%API_TOKEN% >> .env
)

(
    echo.
    echo # Required: Solvhealth Queue URL
    echo SOLVHEALTH_QUEUE_URL=%QUEUE_URL%
    echo.
    echo # Database disabled (API-only mode)
    echo USE_DATABASE=false
    echo.
    echo # Enable API sending
    echo USE_API=true
    echo.
    echo # Playwright headless mode
    echo PLAYWRIGHT_HEADLESS=true
) >> .env

echo OK
echo.

:config_check
echo [5/5] Verifying configuration...
if exist .env (
    echo Configuration file created successfully
    echo.
    echo Configuration saved:
    type .env | findstr /V "^#"
) else (
    echo ERROR: Failed to create .env file
    pause
    exit /b 1
)

echo.
echo ==========================================
echo Setup Complete!
echo ==========================================
echo.
echo Next steps:
echo   1. Review the .env file to ensure all settings are correct
echo   2. Run: python run_all.py
echo.
echo The monitor will:
echo   - Capture patient form data
echo   - Send data to: %API_URL%/patients/create
echo   - NOT require PostgreSQL
echo.
pause

