#!/bin/bash
# Setup script for API-only mode (no database required)

echo "=========================================="
echo "Patient Form Monitor - API-Only Setup"
echo "=========================================="
echo ""

# Check if .env file exists
if [ -f .env ]; then
    echo "⚠️  .env file already exists"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env file"
        exit 0
    fi
fi

# Get API URL
echo "Enter your API endpoint URL (e.g., https://app.example.com):"
read -p "API_URL: " api_url

if [ -z "$api_url" ]; then
    echo "❌ Error: API_URL is required"
    exit 1
fi

# Get Solvhealth Queue URL
echo ""
echo "Enter Solvhealth queue URL (press Enter for default):"
read -p "SOLVHEALTH_QUEUE_URL [https://manage.solvhealth.com/queue?location_ids=AXjwbE]: " queue_url
queue_url=${queue_url:-"https://manage.solvhealth.com/queue?location_ids=AXjwbE"}

# Get API Token (optional)
echo ""
echo "Enter API token (optional, press Enter to skip):"
read -p "API_TOKEN: " api_token

# Create .env file
cat > .env << EOF
# Patient Form Monitor - API-Only Configuration
# Generated by setup-api-only.sh

# Required: API Configuration
API_URL=$api_url
EOF

if [ -n "$api_token" ]; then
    echo "API_TOKEN=$api_token" >> .env
fi

cat >> .env << EOF

# Required: Solvhealth Queue URL
SOLVHEALTH_QUEUE_URL=$queue_url

# Database disabled (API-only mode)
USE_DATABASE=false

# Enable API sending
USE_API=true

# Playwright headless mode
PLAYWRIGHT_HEADLESS=true
EOF

echo ""
echo "✅ Configuration saved to .env file"
echo ""
echo "Configuration:"
echo "  API_URL: $api_url"
echo "  SOLVHEALTH_QUEUE_URL: $queue_url"
echo "  USE_DATABASE: false (API-only mode)"
echo ""
echo "You can now run:"
echo "  python3 run_all.py"
echo ""

